export const PROVIDER_FETCH_DATA_IS_LOADING = 'PROVIDER_FETCH_DATA_IS_LOADING';
export const PROVIDER_FETCH_DATA_HAS_ERRORED = 'PROVIDER_FETCH_DATA_HAS_ERRORED';
export const PROVIDER_FETCH_DATA_SUCCESS = 'PROVIDER_FETCH_DATA_SUCCESS';
export const PROVIDER_SELECT_PROVIDER = 'PROVIDER_SELECT_PROVIDER';

export const TORRENTS_IS_LOADING = 'TORRENTS_IS_LOADING';
export const TORRENTS_HAS_ERRORED = 'TORRENTS_HAS_ERRORED';
export const TORRENTS_FETCH_DATA_SUCCESS = 'TORRENTS_FETCH_DATA_SUCCESS';
export const TORRENTS_SELECT_TORRENT_SUCCESS = 'TORRENTS_SELECT_TORRENT_SUCCESS';