export const PROXY_FETCH_DATA_IS_LOADING = 'PROXY_FETCH_DATA_IS_LOADING';
export const PROXY_FETCH_DATA_HAS_ERRORED = 'PROXY_FETCH_DATA_HAS_ERRORED';
export const PROXY_FETCH_DATA_SUCCESS = 'PROXY_FETCH_DATA_SUCCESS';
export const PROXY_SELECT_PROXY = 'PROXY_SELECT_PROXY';

export const TORRENTS_IS_LOADING = 'TORRENTS_IS_LOADING';
export const TORRENTS_HAS_ERRORED = 'TORRENTS_HAS_ERRORED';
export const TORRENTS_FETCH_DATA_SUCCESS = 'TORRENTS_FETCH_DATA_SUCCESS';
export const TORRENTS_SELECT_TORRENT_SUCCESS = 'TORRENTS_SELECT_TORRENT_SUCCESS';